CRITICAL - 2025-08-24 03:08:08 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:08:10 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:08:10 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:08:11 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:08:11 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:08:11 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:08:45 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:09:09 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:09:19 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:09:22 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:09:23 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:09:38 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:10:45 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:10:46 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:11:57 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "home/index.php"
[Method: GET, Route: /]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('home/index.php')
 2 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('home/index', [], true)
 3 APPPATH\Controllers\Home.php(8): view('home/index')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:12:24 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:12:58 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:20:42 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:25:53 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:25:57 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:28:04 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: SCMS-1/login]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:28:39 --> ErrorException: Maximum execution time of 120 seconds exceeded
[Method: POST, Route: login]
in SYSTEMPATH\Debug\Exceptions.php on line 208.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-08-24 03:28:39 --> ErrorException: Maximum execution time of 120 seconds exceeded
[Method: POST, Route: login]
in SYSTEMPATH\Debug\Exceptions.php on line 208.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-08-24 03:28:39 --> ErrorException: Maximum execution time of 120 seconds exceeded
[Method: POST, Route: login]
in SYSTEMPATH\Debug\Exceptions.php on line 208.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-08-24 03:28:39 --> ErrorException: Maximum execution time of 120 seconds exceeded
[Method: POST, Route: login]
in SYSTEMPATH\Debug\Exceptions.php on line 208.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-08-24 03:28:39 --> ErrorException: Maximum execution time of 120 seconds exceeded
[Method: GET, Route: login]
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-08-24 03:28:39 --> ErrorException: Maximum execution time of 120 seconds exceeded
[Method: POST, Route: login]
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-08-24 03:28:39 --> ErrorException: Maximum execution time of 120 seconds exceeded
[Method: GET, Route: register]
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-08-24 03:28:39 --> ErrorException: Maximum execution time of 120 seconds exceeded
[Method: GET, Route: login]
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-08-24 03:28:39 --> ErrorException: Maximum execution time of 120 seconds exceeded
[Method: GET, Route: login]
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-08-24 03:28:39 --> ErrorException: Maximum execution time of 120 seconds exceeded
[Method: GET, Route: login]
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-08-24 03:29:19 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:29:20 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 03:51:27 --> ErrorException: Maximum execution time of 120 seconds exceeded
[Method: POST, Route: login]
in SYSTEMPATH\Debug\Exceptions.php on line 208.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-08-24 03:52:46 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 03:52:57 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'scms_db', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 03:52:57 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
CRITICAL - 2025-08-24 03:52:57 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 03:53:09 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'scms_db', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 03:53:09 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
CRITICAL - 2025-08-24 03:53:09 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 04:15:07 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 04:15:07 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
CRITICAL - 2025-08-24 04:15:07 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 06:10:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1545): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(646): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 C:\xampp\htdocs\SCMS-1\system\Commands\Database\MigrateStatus.php(115): CodeIgniter\Database\MigrationRunner->getHistory('')
#8 C:\xampp\htdocs\SCMS-1\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\MigrateStatus->run(Array)
#9 C:\xampp\htdocs\SCMS-1\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate:status', Array)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\SCMS-1\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1545): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(646): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 C:\xampp\htdocs\SCMS-1\system\Commands\Database\MigrateStatus.php(115): CodeIgniter\Database\MigrationRunner->getHistory('')
#7 C:\xampp\htdocs\SCMS-1\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\MigrateStatus->run(Array)
#8 C:\xampp\htdocs\SCMS-1\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate:status', Array)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\xampp\htdocs\SCMS-1\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-24 06:10:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: CLI, Route: migrate:status]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FROM `ci4`')
 3 SYSTEMPATH\Database\BaseConnection.php(1545): CodeIgniter\Database\BaseConnection->listTables()
 4 SYSTEMPATH\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
 5 SYSTEMPATH\Database\MigrationRunner.php(646): CodeIgniter\Database\MigrationRunner->ensureTable()
 6 SYSTEMPATH\Commands\Database\MigrateStatus.php(115): CodeIgniter\Database\MigrationRunner->getHistory('')
 7 SYSTEMPATH\CLI\Commands.php(74): CodeIgniter\Commands\Database\MigrateStatus->run([])
 8 SYSTEMPATH\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate:status', [])
 9 SYSTEMPATH\Boot.php(388): CodeIgniter\CLI\Console->run()
10 SYSTEMPATH\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
11 ROOTPATH\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2025-08-24 06:10:42 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1545): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(162): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 C:\xampp\htdocs\SCMS-1\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\SCMS-1\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\SCMS-1\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\SCMS-1\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1545): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(162): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 C:\xampp\htdocs\SCMS-1\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 C:\xampp\htdocs\SCMS-1\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 C:\xampp\htdocs\SCMS-1\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\xampp\htdocs\SCMS-1\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-24 06:10:42 --> ErrorException: require(C:\xampp\htdocs\SCMS-1\app\Views/errors/cli/error_exception.php): Failed to open stream: No such file or directory
[Method: CLI, Route: migrate]
in SYSTEMPATH\CLI\BaseCommand.php on line 133.
 1 SYSTEMPATH\CLI\BaseCommand.php(133): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(C:\\xampp\\htdocs\\SCMS-1\\app\\Views/errors/cli/error_exception.php): Failed to open stream: No such file or directory', 'C:\\xampp\\htdocs\\SCMS-1\\system\\CLI\\BaseCommand.php', 133)
 2 SYSTEMPATH\CLI\BaseCommand.php(133): require()
 3 SYSTEMPATH\Commands\Database\Migrate.php(99): CodeIgniter\CLI\BaseCommand->showError(Object(CodeIgniter\Database\Exceptions\DatabaseException))
 4 SYSTEMPATH\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run([])
 5 SYSTEMPATH\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', [])
 6 SYSTEMPATH\Boot.php(388): CodeIgniter\CLI\Console->run()
 7 SYSTEMPATH\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 8 ROOTPATH\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2025-08-24 06:10:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\SCMS-1\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#5 C:\xampp\htdocs\SCMS-1\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#6 C:\xampp\htdocs\SCMS-1\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#7 C:\xampp\htdocs\SCMS-1\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#8 C:\xampp\htdocs\SCMS-1\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#10 C:\xampp\htdocs\SCMS-1\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\SCMS-1\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#4 C:\xampp\htdocs\SCMS-1\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#5 C:\xampp\htdocs\SCMS-1\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#6 C:\xampp\htdocs\SCMS-1\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#7 C:\xampp\htdocs\SCMS-1\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\SCMS-1\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\SCMS-1\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}
CRITICAL - 2025-08-24 06:10:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: CLI, Route: db:seed/UserSeeder]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
 3 SYSTEMPATH\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(null)
 4 SYSTEMPATH\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
 5 SYSTEMPATH\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run([...])
 6 SYSTEMPATH\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', [...])
 7 SYSTEMPATH\Boot.php(388): CodeIgniter\CLI\Console->run()
 8 SYSTEMPATH\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 9 ROOTPATH\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2025-08-24 06:11:18 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:11:19 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:11:19 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:11:19 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 06:11:35 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 06:11:35 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2025-08-24 06:11:36 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 06:11:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 06:11:53 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2025-08-24 06:11:53 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 06:12:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 06:12:07 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2025-08-24 06:12:07 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:12:17 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:12:17 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:12:17 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 06:25:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 06:25:18 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2025-08-24 06:25:18 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 06:27:04 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1545): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(162): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 C:\xampp\htdocs\SCMS-1\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\SCMS-1\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\SCMS-1\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\SCMS-1\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1545): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(162): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 C:\xampp\htdocs\SCMS-1\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 C:\xampp\htdocs\SCMS-1\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 C:\xampp\htdocs\SCMS-1\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\xampp\htdocs\SCMS-1\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-24 06:27:04 --> ErrorException: require(C:\xampp\htdocs\SCMS-1\app\Views/errors/cli/error_exception.php): Failed to open stream: No such file or directory
[Method: CLI, Route: migrate]
in SYSTEMPATH\CLI\BaseCommand.php on line 133.
 1 SYSTEMPATH\CLI\BaseCommand.php(133): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(C:\\xampp\\htdocs\\SCMS-1\\app\\Views/errors/cli/error_exception.php): Failed to open stream: No such file or directory', 'C:\\xampp\\htdocs\\SCMS-1\\system\\CLI\\BaseCommand.php', 133)
 2 SYSTEMPATH\CLI\BaseCommand.php(133): require()
 3 SYSTEMPATH\Commands\Database\Migrate.php(99): CodeIgniter\CLI\BaseCommand->showError(Object(CodeIgniter\Database\Exceptions\DatabaseException))
 4 SYSTEMPATH\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run([])
 5 SYSTEMPATH\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', [])
 6 SYSTEMPATH\Boot.php(388): CodeIgniter\CLI\Console->run()
 7 SYSTEMPATH\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 8 ROOTPATH\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2025-08-24 06:27:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\SCMS-1\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#5 C:\xampp\htdocs\SCMS-1\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#6 C:\xampp\htdocs\SCMS-1\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#7 C:\xampp\htdocs\SCMS-1\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#8 C:\xampp\htdocs\SCMS-1\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#10 C:\xampp\htdocs\SCMS-1\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\SCMS-1\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#4 C:\xampp\htdocs\SCMS-1\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#5 C:\xampp\htdocs\SCMS-1\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#6 C:\xampp\htdocs\SCMS-1\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#7 C:\xampp\htdocs\SCMS-1\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\SCMS-1\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\SCMS-1\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}
CRITICAL - 2025-08-24 06:27:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: CLI, Route: db:seed/UserSeeder]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
 3 SYSTEMPATH\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(null)
 4 SYSTEMPATH\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
 5 SYSTEMPATH\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run([...])
 6 SYSTEMPATH\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', [...])
 7 SYSTEMPATH\Boot.php(388): CodeIgniter\CLI\Console->run()
 8 SYSTEMPATH\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 9 ROOTPATH\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2025-08-24 06:27:42 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1545): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(646): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 C:\xampp\htdocs\SCMS-1\system\Commands\Database\MigrateStatus.php(115): CodeIgniter\Database\MigrationRunner->getHistory('')
#8 C:\xampp\htdocs\SCMS-1\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\MigrateStatus->run(Array)
#9 C:\xampp\htdocs\SCMS-1\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate:status', Array)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\SCMS-1\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(1545): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 C:\xampp\htdocs\SCMS-1\system\Database\MigrationRunner.php(646): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 C:\xampp\htdocs\SCMS-1\system\Commands\Database\MigrateStatus.php(115): CodeIgniter\Database\MigrationRunner->getHistory('')
#7 C:\xampp\htdocs\SCMS-1\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\MigrateStatus->run(Array)
#8 C:\xampp\htdocs\SCMS-1\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate:status', Array)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\xampp\htdocs\SCMS-1\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-24 06:27:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: CLI, Route: migrate:status]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FROM `ci4`')
 3 SYSTEMPATH\Database\BaseConnection.php(1545): CodeIgniter\Database\BaseConnection->listTables()
 4 SYSTEMPATH\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
 5 SYSTEMPATH\Database\MigrationRunner.php(646): CodeIgniter\Database\MigrationRunner->ensureTable()
 6 SYSTEMPATH\Commands\Database\MigrateStatus.php(115): CodeIgniter\Database\MigrationRunner->getHistory('')
 7 SYSTEMPATH\CLI\Commands.php(74): CodeIgniter\Commands\Database\MigrateStatus->run([])
 8 SYSTEMPATH\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate:status', [])
 9 SYSTEMPATH\Boot.php(388): CodeIgniter\CLI\Console->run()
10 SYSTEMPATH\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
11 ROOTPATH\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2025-08-24 06:29:09 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 06:29:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 06:29:13 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2025-08-24 06:29:13 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 06:29:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 06:29:43 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2025-08-24 06:29:43 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 06:29:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 06:29:50 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2025-08-24 06:29:50 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 06:30:19 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 06:30:19 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2025-08-24 06:30:20 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 06:31:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 06:31:06 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2025-08-24 06:31:06 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 06:31:17 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 06:31:17 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2025-08-24 06:31:17 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-24 06:31:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\SCMS-1\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SCMS-1\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SCMS-1\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SCMS-1\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SCMS-1\system\BaseModel.php(715): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\SCMS-1\app\Controllers\Auth.php(59): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(933): App\Controllers\Auth->loginSubmit()
#7 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\SCMS-1\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SCMS-1\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SCMS-1\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\SCMS-1\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-08-24 06:31:36 --> Login error: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2025-08-24 06:31:36 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:33:11 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:33:11 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:33:11 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:33:16 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:33:55 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:37:00 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:37:01 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:37:15 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:37:36 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:37:37 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:37:42 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: dashboard]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:38:25 --> ErrorException: Undefined property: App\Controllers\Dashboard::$session
[Method: GET, Route: dashboard]
in APPPATH\Controllers\Dashboard.php on line 19.
 1 APPPATH\Controllers\Dashboard.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Dashboard::$session', 'C:\\xampp\\htdocs\\SCMS-1\\app\\Controllers\\Dashboard.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:38:25 --> ErrorException: Undefined property: App\Controllers\Dashboard::$session
[Method: GET, Route: dashboard]
in APPPATH\Controllers\Dashboard.php on line 19.
 1 APPPATH\Controllers\Dashboard.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Dashboard::$session', 'C:\\xampp\\htdocs\\SCMS-1\\app\\Controllers\\Dashboard.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:38:25 --> ErrorException: Undefined property: App\Controllers\Dashboard::$session
[Method: GET, Route: dashboard]
in APPPATH\Controllers\Dashboard.php on line 19.
 1 APPPATH\Controllers\Dashboard.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Dashboard::$session', 'C:\\xampp\\htdocs\\SCMS-1\\app\\Controllers\\Dashboard.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:38:26 --> ErrorException: Undefined property: App\Controllers\Dashboard::$session
[Method: GET, Route: dashboard]
in APPPATH\Controllers\Dashboard.php on line 19.
 1 APPPATH\Controllers\Dashboard.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Dashboard::$session', 'C:\\xampp\\htdocs\\SCMS-1\\app\\Controllers\\Dashboard.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:38:44 --> ErrorException: Undefined property: App\Controllers\Dashboard::$session
[Method: GET, Route: dashboard]
in APPPATH\Controllers\Dashboard.php on line 19.
 1 APPPATH\Controllers\Dashboard.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Dashboard::$session', 'C:\\xampp\\htdocs\\SCMS-1\\app\\Controllers\\Dashboard.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:39:07 --> ErrorException: Undefined property: App\Controllers\Dashboard::$session
[Method: GET, Route: dashboard]
in APPPATH\Controllers\Dashboard.php on line 19.
 1 APPPATH\Controllers\Dashboard.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Dashboard::$session', 'C:\\xampp\\htdocs\\SCMS-1\\app\\Controllers\\Dashboard.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:39:39 --> Error: Class "App\Controllers\Errors" not found
[Method: GET, Route: favicon.ico]
in SYSTEMPATH\CodeIgniter.php on line 903.
 1 SYSTEMPATH\CodeIgniter.php(965): CodeIgniter\CodeIgniter->createController()
 2 SYSTEMPATH\CodeIgniter.php(360): CodeIgniter\CodeIgniter->display404errors(Object(CodeIgniter\Exceptions\PageNotFoundException))
 3 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 4 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 5 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:39:41 --> ErrorException: Undefined property: App\Controllers\Dashboard::$session
[Method: GET, Route: dashboard]
in APPPATH\Controllers\Dashboard.php on line 19.
 1 APPPATH\Controllers\Dashboard.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Dashboard::$session', 'C:\\xampp\\htdocs\\SCMS-1\\app\\Controllers\\Dashboard.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:40:05 --> ErrorException: Undefined property: App\Controllers\Dashboard::$session
[Method: GET, Route: dashboard]
in APPPATH\Controllers\Dashboard.php on line 19.
 1 APPPATH\Controllers\Dashboard.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Dashboard::$session', 'C:\\xampp\\htdocs\\SCMS-1\\app\\Controllers\\Dashboard.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-24 06:40:07 --> ErrorException: Undefined property: App\Controllers\Dashboard::$session
[Method: GET, Route: dashboard]
in APPPATH\Controllers\Dashboard.php on line 19.
 1 APPPATH\Controllers\Dashboard.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Dashboard::$session', 'C:\\xampp\\htdocs\\SCMS-1\\app\\Controllers\\Dashboard.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(64): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
